// automatically generated by the FlatBuffers compiler, do not modify

package io.github.api7.A6.Err;

public final class Code {
  private Code() { }
  public static final int BAD_REQUEST = 0;
  public static final int SERVICE_UNAVAILABLE = 1;
  public static final int CONF_TOKEN_NOT_FOUND = 2;

  public static final String[] names = { "BAD_REQUEST", "SERVICE_UNAVAILABLE", "CONF_TOKEN_NOT_FOUND", };

  public static String name(int e) { return names[e]; }
}

