// automatically generated by the FlatBuffers compiler, do not modify

package io.github.api7.A6.Err;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Resp extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Resp getRootAsResp(ByteBuffer _bb) { return getRootAsResp(_bb, new Resp()); }
  public static Resp getRootAsResp(ByteBuffer _bb, Resp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Resp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int code() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createResp(FlatBufferBuilder builder,
      int code) {
    builder.startTable(1);
    Resp.addCode(builder, code);
    return Resp.endResp(builder);
  }

  public static void startResp(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addCode(FlatBufferBuilder builder, int code) { builder.addByte(0, (byte)code, (byte)0); }
  public static int endResp(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Resp get(int j) { return get(new Resp(), j); }
    public Resp get(Resp obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

