// automatically generated by the FlatBuffers compiler, do not modify

package A6;

public final class Method {
  private Method() { }
  public static final int GET = 0;
  public static final int HEAD = 1;
  public static final int POST = 2;
  public static final int PUT = 3;
  public static final int DELETE = 4;
  public static final int MKCOL = 5;
  public static final int COPY = 6;
  public static final int MOVE = 7;
  public static final int OPTIONS = 8;
  public static final int PROPFIND = 9;
  public static final int PROPPATCH = 10;
  public static final int LOCK = 11;
  public static final int UNLOCK = 12;
  public static final int PATCH = 13;
  public static final int TRACE = 14;

  public static final String[] names = { "GET", "HEAD", "POST", "PUT", "DELETE", "MKCOL", "COPY", "MOVE", "OPTIONS", "PROPFIND", "PROPPATCH", "LOCK", "UNLOCK", "PATCH", "TRACE", };

  public static String name(int e) { return names[e]; }
}

