// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResp(bb:flatbuffers.ByteBuffer, obj?:Resp):Resp {
  return (obj || new Resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResp(bb:flatbuffers.ByteBuffer, obj?:Resp):Resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

confToken():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startResp(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addConfToken(builder:flatbuffers.Builder, confToken:number) {
  builder.addFieldInt32(0, confToken, 0);
}

static endResp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResp(builder:flatbuffers.Builder, confToken:number):flatbuffers.Offset {
  Resp.startResp(builder);
  Resp.addConfToken(builder, confToken);
  return Resp.endResp(builder);
}
}
