// automatically generated by the FlatBuffers compiler, do not modify

import { Rewrite } from '../../a6/h-t-t-p-req-call/rewrite';
import { Stop } from '../../a6/h-t-t-p-req-call/stop';


export enum Action{
  NONE = 0,
  Stop = 1,
  Rewrite = 2
}

export function unionToAction(
  type: Action,
  accessor: (obj:Rewrite|Stop) => Rewrite|Stop|null
): Rewrite|Stop|null {
  switch(Action[type]) {
    case 'NONE': return null; 
    case 'Stop': return accessor(new Stop())! as Stop;
    case 'Rewrite': return accessor(new Rewrite())! as Rewrite;
    default: return null;
  }
}

export function unionListToAction(
  type: Action, 
  accessor: (index: number, obj:Rewrite|Stop) => Rewrite|Stop|null, 
  index: number
): Rewrite|Stop|null {
  switch(Action[type]) {
    case 'NONE': return null; 
    case 'Stop': return accessor(index, new Stop())! as Stop;
    case 'Rewrite': return accessor(index, new Rewrite())! as Rewrite;
    default: return null;
  }
}

