-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: A6

local flatbuffers = require('flatbuffers')

local DataEntry = {} -- the module
local DataEntry_mt = {} -- the class metatable

function DataEntry.New()
    local o = {}
    setmetatable(o, {__index = DataEntry_mt})
    return o
end
function DataEntry.GetRootAsDataEntry(buf, offset)
    if type(buf) == "string" then
        buf = flatbuffers.binaryArray.New(buf)
    end
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = DataEntry.New()
    o:Init(buf, n + offset)
    return o
end
function DataEntry_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function DataEntry_mt:Name()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function DataEntry_mt:Value(j)
    local o = self.view:Offset(6)
    if o ~= 0 then
        local a = self.view:Vector(o)
        return self.view:Get(flatbuffers.N.Uint8, a + ((j-1) * 1))
    end
    return 0
end
function DataEntry_mt:ValueAsString(start, stop)
    return self.view:VectorAsString(6, start, stop)
end
function DataEntry_mt:ValueLength()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function DataEntry.Start(builder) builder:StartObject(2) end
function DataEntry.AddName(builder, name) builder:PrependUOffsetTRelativeSlot(0, name, 0) end
function DataEntry.AddValue(builder, value) builder:PrependUOffsetTRelativeSlot(1, value, 0) end
function DataEntry.StartValueVector(builder, numElems) return builder:StartVector(1, numElems, 1) end
function DataEntry.End(builder) return builder:EndObject() end

return DataEntry -- return the module