// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ExtraInfo

import "strconv"

type Info byte

const (
	InfoNONE    Info = 0
	InfoVar     Info = 1
	InfoReqBody Info = 2
)

var EnumNamesInfo = map[Info]string{
	InfoNONE:    "NONE",
	InfoVar:     "Var",
	InfoReqBody: "ReqBody",
}

var EnumValuesInfo = map[string]Info{
	"NONE":    InfoNONE,
	"Var":     InfoVar,
	"ReqBody": InfoReqBody,
}

func (v Info) String() string {
	if s, ok := EnumNamesInfo[v]; ok {
		return s
	}
	return "Info(" + strconv.FormatInt(int64(v), 10) + ")"
}
