// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ExtraInfo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Req struct {
	_tab flatbuffers.Table
}

func GetRootAsReq(buf []byte, offset flatbuffers.UOffsetT) *Req {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Req{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsReq(buf []byte, offset flatbuffers.UOffsetT) *Req {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Req{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Req) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Req) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Req) InfoType() Info {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Info(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Req) MutateInfoType(n Info) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Req) Info(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReqAddInfoType(builder *flatbuffers.Builder, infoType Info) {
	builder.PrependByteSlot(0, byte(infoType), 0)
}
func ReqAddInfo(builder *flatbuffers.Builder, info flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(info), 0)
}
func ReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
