// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ExtraInfo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReqBody struct {
	_tab flatbuffers.Table
}

func GetRootAsReqBody(buf []byte, offset flatbuffers.UOffsetT) *ReqBody {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReqBody{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsReqBody(buf []byte, offset flatbuffers.UOffsetT) *ReqBody {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReqBody{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ReqBody) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReqBody) Table() flatbuffers.Table {
	return rcv._tab
}

func ReqBodyStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ReqBodyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
