// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ExtraInfo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Resp struct {
	_tab flatbuffers.Table
}

func GetRootAsResp(buf []byte, offset flatbuffers.UOffsetT) *Resp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resp{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResp(buf []byte, offset flatbuffers.UOffsetT) *Resp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Resp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Resp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Resp) Result(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Resp) ResultLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Resp) ResultBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Resp) MutateResult(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func RespStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RespAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func RespStartResultVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
