// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ExtraInfo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Var struct {
	_tab flatbuffers.Table
}

func GetRootAsVar(buf []byte, offset flatbuffers.UOffsetT) *Var {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Var{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsVar(buf []byte, offset flatbuffers.UOffsetT) *Var {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Var{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Var) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Var) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Var) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func VarStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VarAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func VarEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
