// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package HTTPReqCall

import "strconv"

type Action byte

const (
	ActionNONE    Action = 0
	ActionStop    Action = 1
	ActionRewrite Action = 2
)

var EnumNamesAction = map[Action]string{
	ActionNONE:    "NONE",
	ActionStop:    "Stop",
	ActionRewrite: "Rewrite",
}

var EnumValuesAction = map[string]Action{
	"NONE":    ActionNONE,
	"Stop":    ActionStop,
	"Rewrite": ActionRewrite,
}

func (v Action) String() string {
	if s, ok := EnumNamesAction[v]; ok {
		return s
	}
	return "Action(" + strconv.FormatInt(int64(v), 10) + ")"
}
