// automatically generated by the FlatBuffers compiler, do not modify

package io.github.api7.A6.ExtraInfo;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ReqBody extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static ReqBody getRootAsReqBody(ByteBuffer _bb) { return getRootAsReqBody(_bb, new ReqBody()); }
  public static ReqBody getRootAsReqBody(ByteBuffer _bb, ReqBody obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ReqBody __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startReqBody(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endReqBody(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ReqBody get(int j) { return get(new ReqBody(), j); }
    public ReqBody get(ReqBody obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

