// automatically generated by the FlatBuffers compiler, do not modify

package io.github.api7.A6.ExtraInfo;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Resp extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Resp getRootAsResp(ByteBuffer _bb) { return getRootAsResp(_bb, new Resp()); }
  public static Resp getRootAsResp(ByteBuffer _bb, Resp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Resp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int result(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int resultLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector resultVector() { return resultVector(new ByteVector()); }
  public ByteVector resultVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer resultAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer resultInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createResp(FlatBufferBuilder builder,
      int resultOffset) {
    builder.startTable(1);
    Resp.addResult(builder, resultOffset);
    return Resp.endResp(builder);
  }

  public static void startResp(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addResult(FlatBufferBuilder builder, int resultOffset) { builder.addOffset(0, resultOffset, 0); }
  public static int createResultVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createResultVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startResultVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endResp(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Resp get(int j) { return get(new Resp(), j); }
    public Resp get(Resp obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

