// automatically generated by the FlatBuffers compiler, do not modify

package io.github.api7.A6.HTTPReqCall;

@SuppressWarnings("unused")
public final class Action {
  private Action() { }
  public static final byte NONE = 0;
  public static final byte Stop = 1;
  public static final byte Rewrite = 2;

  public static final String[] names = { "NONE", "Stop", "Rewrite", };

  public static String name(int e) { return names[e]; }
}

