-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ExtraInfo

local Info = {
    NONE = 0,
    Var = 1,
    ReqBody = 2,
    RespBody = 3,
}

return Info -- return the module