-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ExtraInfo

local flatbuffers = require('flatbuffers')

local ReqBody = {} -- the module
local ReqBody_mt = {} -- the class metatable

function ReqBody.New()
    local o = {}
    setmetatable(o, {__index = ReqBody_mt})
    return o
end
function ReqBody.GetRootAsReqBody(buf, offset)
    if type(buf) == "string" then
        buf = flatbuffers.binaryArray.New(buf)
    end
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ReqBody.New()
    o:Init(buf, n + offset)
    return o
end
function ReqBody_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function ReqBody.Start(builder) builder:StartObject(0) end
function ReqBody.End(builder) return builder:EndObject() end

return ReqBody -- return the module