# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PrepareConf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Resp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Resp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Resp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Resp
    def ConfToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(1)
def RespStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddConfToken(builder, confToken): builder.PrependUint32Slot(0, confToken, 0)
def RespAddConfToken(builder, confToken):
    """This method is deprecated. Please switch to AddConfToken."""
    return AddConfToken(builder, confToken)
def End(builder): return builder.EndObject()
def RespEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)