// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Err

import "strconv"

type Code byte

const (
	CodeBAD_REQUEST          Code = 0
	CodeSERVICE_UNAVAILABLE  Code = 1
	CodeCONF_TOKEN_NOT_FOUND Code = 2
)

var EnumNamesCode = map[Code]string{
	CodeBAD_REQUEST:          "BAD_REQUEST",
	CodeSERVICE_UNAVAILABLE:  "SERVICE_UNAVAILABLE",
	CodeCONF_TOKEN_NOT_FOUND: "CONF_TOKEN_NOT_FOUND",
}

var EnumValuesCode = map[string]Code{
	"BAD_REQUEST":          CodeBAD_REQUEST,
	"SERVICE_UNAVAILABLE":  CodeSERVICE_UNAVAILABLE,
	"CONF_TOKEN_NOT_FOUND": CodeCONF_TOKEN_NOT_FOUND,
}

func (v Code) String() string {
	if s, ok := EnumNamesCode[v]; ok {
		return s
	}
	return "Code(" + strconv.FormatInt(int64(v), 10) + ")"
}
