// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Err

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Resp struct {
	_tab flatbuffers.Table
}

func GetRootAsResp(buf []byte, offset flatbuffers.UOffsetT) *Resp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resp{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResp(buf []byte, offset flatbuffers.UOffsetT) *Resp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Resp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Resp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Resp) Code() Code {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Code(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Resp) MutateCode(n Code) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func RespStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RespAddCode(builder *flatbuffers.Builder, code Code) {
	builder.PrependByteSlot(0, byte(code), 0)
}
func RespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
