-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Err

local Code = {
    BAD_REQUEST = 0,
    SERVICE_UNAVAILABLE = 1,
    CONF_TOKEN_NOT_FOUND = 2,
}

return Code -- return the module